import QUEUE_ACTIONS, { QUEUE_ACTION_TYPES } from './queue';

const ACTIONS = {};
ACTIONS[QUEUE_ACTION_TYPES.REMOVE_TRACK_FROM_QUEUE] = QUEUE_ACTIONS[QUEUE_ACTION_TYPES.REMOVE_TRACK_FROM_QUEUE];

export default ACTIONS;
