const ARE_AND_BE = {
  name: 'Are & Be',
  trackQueries: [
    "Run Me Dry Bryson Tiller",
    "Die For You The Weeknd",
    "For You SoMo",
    "Questions Chris Brown",
    "Ex (feat. YG) Ty Dolla $ign, YG",
    "The Weekend SZA",
    "Insecure Jazmine Sullivan, Bryson Tiller",
    "Best Part (feat. H.E.R.) Daniel Caesar, H.E.R.",
    "While We're Young Jhene Aiko",
    "Song Goes Off Trey Songz",
    "When We Tank",
    "Wild Thoughts DJ Khaled, Rihanna, Bryson Tiller",
    "At The Club Jacquees, DeJ Loaf",
    "Sky Walker Miguel, Travis Scott",
    "Love U Better (feat. Lil Wayne & The-Dream) Ty Dolla $ign, Lil Wayne, The-Dream",
    "Love Galore SZA, Travis Scott",
    "Mood dvsn",
    "2 H.E.R.",
    "Everybody Knows Chris Brown",
    "Incapable Keyshia Cole",
    "Versace On The Floor Bruno Mars",
    "Loved By You Mali Music, Jazmine Sullivan",
    "Come Through and Chill Salaam Remi, Miguel",
    "Temperature Devvon Terrell",
    "Drip Luke James",
    "Blind Man Xavier Omär",
    "Prototype Kevin Ross",
    "Before I Do Sevyn Streeter",
    "Either Way (feat. Chris Brown) K. Michelle, Chris Brown",
    "Don't Matter August Alsina",
    "Skrt Skrt Tory Lanez",
    "Only 4 Me Chris Brown, Ty Dolla $ign, Verse Simmonds",
    "Want More Rotimi, Kranium",
    "Told You So Miguel",
    "Thinking ‘Bout You (Sleepless In Cairo) Sufyvn, BJ The Chicago Kid",
    "Lights On H.E.R.",
    "Wanna Be Yours Guordan Banks",
    "Complicated MIKExANGEL",
    "Nowhere Chris Brown",
    "Quicksand SZA",
    "Better Man (feat. Rick Ross) PARTYNEXTDOOR, Rick Ross",
    "Provider Frank Ocean",
    "Give You More Ledisi, John Legend",
    "Blind Tamar Braxton",
    "Another Love Song Ne-Yo",
    "B.E.D. Jacquees",
    "Grey Luh Berhana",
    "Luh Ya Marsha Ambrosius",
    "IMAGINATION Adrian Marcel",
    "Think About Me dvsn",
  ],
};

const ROCK_CLASSICS = {
  name: 'Rock Classics',
  trackQueries: [
    "Ain't That A Shame? - 2002 Digital Remaster Fats Domino",
    "Come Together - Remastered The Beatles",
    "Immigrant Song Led Zeppelin",
    "Free Fallin' Tom Petty",
    "Back In Black AC/DC",
    "House Of The Rising Sun The Animals",
    "Paint It, Black - Mono / Remastered The Rolling Stones",
    "Have You Ever Seen The Rain? Creedence Clearwater Revival",
    "Paradise City Guns N' Roses",
    "Should I Stay or Should I Go - Remastered The Clash",
    "Dream On Aerosmith",
    "Whole Lotta Love Led Zeppelin",
    "Another One Bites The Dust Queen",
    "Sweet Home Alabama Lynyrd Skynyrd",
    "Sultans Of Swing Dire Straits",
    "La Grange - 2005 Remastered Version ZZ Top",
    "Sweet Child O' Mine Guns N' Roses",
    "Bohemian Rhapsody Queen",
    "Welcome To The Jungle Guns N' Roses",
    "Carry on Wayward Son Kansas",
    "Layla - 40th Anniversary Version / 2010 Remastered Derek & The Dominos",
    "Dirty Deeds Done Dirt Cheap AC/DC",
    "Bad Moon Rising Creedence Clearwater Revival",
    "The Chain - 2004 Remastered Edition Fleetwood Mac",
    "Edge of Seventeen - Remastered Stevie Nicks",
    "Money Pink Floyd",
    "Highway to Hell AC/DC",
    "Hotel California - Live at The Los Angeles Forum, 10/20-22/76 Eagles",
    "All Right Now Free",
    "Born To Be Wild Steppenwolf",
    "Another Brick in the Wall, Pt. 2 Pink Floyd",
    "Gimme Shelter The Rolling Stones",
    "Cocaine Eric Clapton",
    "Listen To The Music The Doobie Brothers",
    "Simple Man Lynyrd Skynyrd",
    "Old Time Rock & Roll Bob Seger",
    "Sunshine Of Your Love Cream",
    "Dust in the Wind Kansas",
    "Don't Stop Believin' Journey",
    "Pour Some Sugar On Me (2012) Def Leppard",
    "Free Bird Lynyrd Skynyrd",
    "Long Cool Woman (In A Black Dress) - 1999 Remastered Version The Hollies",
    "All Along the Watchtower Jimi Hendrix",
    "Paranoid - Remastered Version Black Sabbath",
    "Walk This Way Aerosmith",
    "Baba O'Riley The Who",
    "(I Can't Get No) Satisfaction - Mono Version / Remastered 2002 The Rolling Stones",
    "Sharp Dressed Man - 2008 Remastered Version ZZ Top",
    "For What It's Worth Buffalo Springfield",
    "Kashmir Led Zeppelin",
    "Won't Get Fooled Again - Remix The Who",
    "Bang a Gong (Get It On) - Remastered Version T. Rex",
    "Rebel Rebel - 2016 Remastered Version David Bowie",
    "Radar Love Golden Earring",
    "Ramble On Led Zeppelin",
    "Knockin' On Heaven's Door - Remastered Bob Dylan",
    "Riders On The Storm The Doors",
    "Fortunate Son Creedence Clearwater Revival",
    "Beast Of Burden - Remastered The Rolling Stones",
    "Stranglehold Ted Nugent",
    "(Don't Fear) The Reaper Blue Öyster Cult",
    "Crazy Train - Remastered Ozzy Osbourne",
    "Mississippi Queen Mountain",
    "Down On The Corner Creedence Clearwater Revival",
    "Barracuda Heart",
    "Iron Man - Remastered Version Black Sabbath",
    "Brown Eyed Girl Van Morrison",
    "Sweet Emotion Aerosmith",
    "The Joker Steve Miller Band",
    "You Really Got Me - Mono Mix The Kinks",
    "Magic Carpet Ride Steppenwolf",
    "Behind Blue Eyes The Who",
    "Purple Haze Jimi Hendrix",
    "American Pie Don McLean",
    "Break On Through (To The Other Side) The Doors",
    "More Than a Feeling Boston",
    "Life In The Fast Lane - Remastered Eagles",
    "Life's Been Good Joe Walsh",
    "Runnin' With The Devil - 2015 Remastered Version Van Halen",
    "Here I Go Again 87 - 2017 Remastered Version Whitesnake",
    "We Will Rock You - Remastered 2011 Queen",
    "Rock And Roll All Nite KISS",
    "Go Your Own Way - 2004 Remastered Edition Fleetwood Mac",
    "Good Times Bad Times Led Zeppelin",
    "Long Train Runnin' The Doobie Brothers",
    "Pinball Wizard The Who",
    "Brown Sugar - Remastered The Rolling Stones",
    "Light My Fire The Doors",
    "White Room Cream",
    "D'yer Mak'er Led Zeppelin",
    "Honky Tonk Women The Rolling Stones",
    "Gimme Three Steps Lynyrd Skynyrd",
    "Walk On the Wild Side Lou Reed",
    "Peace of Mind Boston",
    "Revolution - Remastered The Beatles",
    "Midnight Rider The Allman Brothers Band",
    "Can't You See The Marshall Tucker Band",
    "Piece of My Heart Big Brother & The Holding Company, Janis Joplin",
    "Love Her Madly The Doors",
    "Hey Joe Jimi Hendrix",
  ],
};

const CHRISTMAS_CLASSICS = {
  name: 'Christmas Classics',
  trackQueries: [
    "Rockin' Around The Christmas Tree Brenda Lee",
    "It's Beginning to Look a Lot Like Christmas Perry Como, The Fontane Sisters, Mitchell Ayres & His Orchestra",
    "Jingle Bell Rock Bobby Helms",
    "A Holly Jolly Christmas Burl Ives",
    "Let It Snow! Let It Snow! Let It Snow! Frank Sinatra, B. Swanson Quartet",
    "Carol of the Bells Mykola Dmytrovych Leontovych, Peter J. Wilhousky, John Williams",
    "It's the Most Wonderful Time of the Year Andy Williams",
    "Winter Wonderland - 2006 - Remaster Bing Crosby",
    "The Christmas Song (Merry Christmas To You) Nat King Cole",
    "Silver Bells Dean Martin",
    "Sleigh Ride Carpenters",
    "Let's Start the New Year Right Bing Crosby",
    "Rudolph The Red Nosed Reindeer Burl Ives",
    "I'll Be Home for Christmas Tony DeSare",
    "White Christmas Bing Crosby, Ken Darby Singers, John Scott Trotter & His Orchestra",
    "Do You Hear What I Hear? - 2006 - Remaster Bing Crosby",
    "Joy To The World Nat King Cole",
    "The First Noel - 1999 - Remaster Frank Sinatra",
    "Blue Christmas Elvis Presley",
    "You're A Mean One, Mr. Grinch Thurl Ravenscroft",
    "Run Rudolph Run - Single Version Chuck Berry",
    "The Little Drummer Boy - 24-Bit Digitally Remastered 99 Bing Crosby",
    "Frosty the Snowman Jimmy Durante",
    "Christmas Time Is Here - Vocal / Album Version Vince Guaraldi Trio",
    "Here We Come a-Caroling / We Wish You a Merry Christmas - Remastered Perry Como",
    "Christmas Time The Platters",
    "Medley: Caroling, Caroling / The First Noel / Hark! The Herald Angels Sing / Silent Night Perry Como",
    "Last Christmas Wham!",
    "Do They Know It's Christmas? Band Aid",
    "Silent Night Carpenters",
    "The Happiest Christmas Tree Nat King Cole",
    "O Christmas Tree Tony Bennett",
    "All I Want For Christmas (Is My Two Front Teeth) - 1997 Digital Remaster Nat King Cole Trio",
    "The Christmas Waltz Peggy Lee",
    "Merry Christmas Darling - Album Version/Remix Carpenters",
    "(Everybody's Waitin' For) The Man With The Bag - Remastered Kay Starr",
    "God Rest Ye Merry Gentlemen Bing Crosby",
    "Mele Kalikimaka - Single Version Bing Crosby, The Andrews Sisters",
    "What Child Is This?/The Holly and the Ivy (Medley) - 2006 - Remaster Bing Crosby",
    "Sleigh Ride Andy Williams",
    "Mistletoe And Holly Frank Sinatra",
  ],
};

const GOLD_SCHOOL = {
  name: 'Gold School',
  trackQueries: [
    "Hey Ma Cam’ron, Juelz Santana, Freekey Zeekey, Toya",
    "There It Go (The Whistle Song) Juelz Santana",
    "Pop Champagne - Explicit Album Version Jim Jones, Ron Browz, Juelz Santana",
    "Dipset Anthem The Diplomats, Cam’ron, Juelz Santana",
    "Dipset (Santana's Town) Juelz Santana, Cam’ron",
    "Certified Gangstas - Remix Jim Jones, The Game, Cam’ron",
    "Oh Boy Cam’ron, Juelz Santana",
    "Once Upon a Time The Diplomats",
    "Welcome To New York City Cam’ron, JAY Z, Juelz Santana",
    "Down And Out Cam’ron, Kanye West, Syleena Johnson",
    "Killa Cam / Roll That Skit Cam’ron",
    "I Really Mean It The Diplomats, Cam’ron, Jimmy Jones",
    "We Fly High Jim Jones",
    "What Means The World To You Cam’ron",
    "Horse & Carriage Cam’ron, Mase",
    "Lean Cam’ron",
    "Summer Wit' Miami Jim Jones, Trey Songz",
    "Back To The Crib Juelz Santana, Chris Brown",
    "Get 'Em Girls / The Mizzle Outro Cam’ron",
    "Sippin' Sizzurp - Remix Diplomats, Three 6 Mafia, Bun B",
    "Hello (feat. Don Q) Cam’ron, Don Q",
    "Dipset Symphony (feat. Juelz Santana, Mim Jones, Hell Rell, JR Writer, 40 Cal, Un Kasa) Dipset, 40 Cal., Hell Rell, Jim Jones, JR Writer, Juelz Santana, Un Kasa",
    "Banned From T.V. Noreaga featuring Big Pun, Jadakiss & Styles (of the L.O.X), Nature, Cam'Ron N.O.R.E., Big Pun, Jadakiss, Styles, Nature, Cam’ron",
    "Reppin' Time Jim Jones",
    "Coleslaw Cam’ron",
  ],
};

const ULTIMATE_INDIE = {
  name: 'Ultimate Indie',
  trackQueries: [
    "Yam Yam No Vacation",
    "Panopticon Cloud Control",
    "Nervous Magic Bronson",
    "Chateau Angus & Julia Stone",
    "Super Natural Turnover",
    "Appointments Julien Baker",
    "Still Beating Mac Demarco",
    "Paola Shout Out Louds",
    "Begin (feat. Wales) Shallou, Wales",
    "Alison Swimming Tapes",
    "You Would Have to Lose Your Mind The Barr Brothers",
    "Come Home The Undercover Dream Lovers",
    "Astronaut - Something About Your Love Mansionair",
    "On Script Courtney Barnett, Kurt Vile",
    "Feeling Grad Party",
    "Magic Tide Frills",
    "Thin Aquilo",
    "Fix Me Beck",
    "Going Home Twist",
    "Bike Dream Rostam",
    "Bad Ones (feat. Tegan and Sara) Matthew Dear, Tegan and Sara",
    "Dive Tim Atlas",
    "Compromised Tim Atlas",
    "Pain The War On Drugs",
    "Tailwhip Men I Trust",
    "Defibrillation The Barr Brothers, Lucius",
    "Spiral Wye Oak",
    "Floating Marlin's Dreaming",
    "Mystik Tash Sultana",
    "Little Dark Age MGMT",
    "Live Well Palace",
    "Mind Hijacker's Curse Chad VanGaalen",
    "Black Out Days - Future Islands Remix Phantogram, Future Islands",
    "Surf Common Tiger",
    "I Saw The End Ardency",
    "Not My Baby Alvvays",
    "Carnation Yumi Zouma",
    "Mountain To Move Nick Mulvey",
    "The Sun Myd",
    "Hawaiian License Plates. Jaws of Love.",
    "Beam Petit Biscuit",
    "Vow TENDER",
    "Born to Beg The National",
    "Dissolve Kllo",
    "Olly Cape Francis",
    "lucid slenderbodies",
    "Yours Now, Now",
    "They Came Along Haulm",
    "Continental Breakfast Courtney Barnett, Kurt Vile",
    "After Slice Ivory Waves",
  ],
};

const TOTALLY_ALTERNATIVE = {
  name: 'Totally Alternative',
  trackQueries: [
    "Freeze Me Death From Above 1979",
    "So Tied Up - moreBishop Cold War Kids, Bishop Briggs",
    "I Only Lie When I Love You Royal Blood",
    "Light The Way Mikky Ekko",
    "Swallow Teenage Wrist",
    "Bottom Of The Deep Blue Sea MISSIO",
    "Fight Milk Only Shadows",
    "Giver K.Flay",
    "Coming Down Big Spring",
    "Youth Hundredth",
    "Holy Mountain Noel Gallagher's High Flying Birds",
    "Sober Up AJR, Rivers Cuomo",
    "Ceasefire Judas",
    "Fire Alarm Castlecomer",
    "Sickago - Bonus Track Deaf Havana",
    "Heel Theme Mansions",
    "Little One Highly Suspect",
    "Young Lady, You're Scaring Me Ron Gallo",
    "T-Shirt Song DON BROCO",
    "Passion AWOLNATION",
    "Whatever Forever Sego",
    "Thank God I'm Not You Himalayas",
    "We Fight Dashboard Confessional",
    "High Sir Sly",
    "hometown cleopatrick",
    "Hold It Down Island Apollo",
    "Painkiller DREAMERS",
    "It's A Trip! Joywave",
    "Captivate You Marmozets",
    "Everything Is Alright The Glorious Sons",
    "Bury Me Face Down grandson",
    "Safari Song Greta Van Fleet",
    "I Found God Mainland",
    "Be Your Man Demob Happy",
    "Had Enough Lower Than Atlantis",
    "They Put A Body In The Bayou The Orwells",
    "Black Holes (Solid Ground) The Blue Stones",
    "Levitate The Palms",
    "Enter Entirely Cloud Nothings",
    "Sea Change Thrice",
    "Someday Pale Seas",
    "Washed Up Bel Heir",
    "Thunder Mondo Cozmo",
    "Walk On Water Thirty Seconds To Mars",
    "The Way You Used To Do Queens of the Stone Age",
    "Pretty Girls on Bikes dubé",
    "I Love You, Will You Marry Me YUNGBLUD",
    "The Deepest Sighs, the Frankest Shadows Gang of Youths",
    "Golden Age Late Night Episode",
    "Baby Royal Republic",
    "Jet Citizen",
    "Undone Paerish",
    "Sawed Off Shotgun The Glorious Sons",
    "Coke BLOXX",
    "Love Is Mystical Cold War Kids",
    "Amsterdam Nothing But Thieves",
    "Whole Wide World - Unpeeled Cage The Elephant",
    "Misery - Single Version Creeper",
    "Near To The Wild Heart Of Life Japandroids",
    "Bad Things Goodbye June",
    "Muthafucka Beware Of Darkness",
    "What's Wrong Pvris",
    "Heroin - Rock Edit Badflower",
    "Wouldn't Wanna Be Ya YONAKA",
    "I Want Mantra",
    "Twice Catfish and the Bottlemen",
    "Blood In The Cut K.Flay",
    "Run Rabbit Run Black Map",
    "Willow Tree Twin Wild",
    "In and Out Blonder",
    "Saviour Mallory Knox",
    "Middle Fingers MISSIO",
    "Memorandum gP.",
    "Automatic Mondo Cozmo",
    "She Said Sundara Karma",
    "Kids (Ain't All Right) Grace Mitchell",
    "Adore Amy Shark",
    "Curse the Weather Royal Tusk",
    "Machine Deadfellow",
    "Silvertongue Young the Giant",
    "PEACE & LOVE VANT",
    "In the Middle Mona",
    "Lullaby Frank Carter & The Rattlesnakes",
    "Daisy Goodbye June",
    "Facing My Fear Cortes",
    "Happy Pills Weathers",
    "White Noise Badflower",
    "Highway Bleeker",
    "Promise Everything Basement",
    "Broken Bones CRX",
    "One Foot Airways",
    "Terrible Things The Orphan The Poet",
    "Favorite Liar The Wrecks",
    "We Could Be The Hunna",
    "Below White Lung",
    "Keep Your Disease Bloodboy",
    "Black Mire Lonely The Brave",
    "Stoned, Alone Teenage Wrist",
    "The End The Beta Machine",
    "Smile More Deap Vally",
  ],
};

const HOT_COUNTRY = {
  name: 'Hot Country',
  trackQueries: [
    "The Rest of Our Life Tim McGraw, Faith Hill",
    "Singles You Up Jordan Davis",
    "In Case You Didn't Know Brett Young",
    "Nothin Like Us Josh Gracin",
    "Take Back Home Girl (Feat. Tori Kelly) Chris Lane, Tori Kelly",
    "Stupid Levi Hummon",
    "When the Good Guys Win Granger Smith",
    "Heaven Kane Brown",
    "Craving You Thomas Rhett, Maren Morris",
    "Almost Over You Jessie James Decker, Randy Houser",
    "I'd Be Jealous Too Dustin Lynch",
    "What Guy Wouldn't Waterloo Revival",
    "All On Me Devin Dawson",
    "Body Like A Back Road Sam Hunt",
    "Devil Callin' Me Back Tim McGraw, Faith Hill",
    "Found You Kane Brown",
    "Light It Up Luke Bryan",
    "Unforgettable Thomas Rhett",
    "Losing Sleep Chris Young",
    "Round Here Buzz Eric Church",
    "This Night Back Canaan Smith",
    "Hooked Dylan Scott",
    "I'll Name the Dogs Blake Shelton",
    "Greatest Love Story LANCO",
    "You Broke Up with Me Walker Hayes",
    "Up Down (Feat. Florida Georgia Line) Morgan Wallen, Florida Georgia Line",
    "Speakers, Bleachers And Preachers Brandon Lay",
    "I Got You Josh Mirenda",
    "Female Keith Urban",
    "Whole Lot in Love Austin Burke",
    "Man Enough Now Chris Bandi",
    "I Could Use a Love Song Maren Morris",
    "Heartache On The Dance Floor Jon Pardi",
    "Be with Me Old Dominion",
    "Stay Downtown Cole Swindell",
    "Look At You Seth Ennis",
    "Three Chords & The Truth Chase Rice",
    "Kiss Somebody Morgan Evans",
    "Like I Loved You Brett Young",
    "Yours Russell Dickerson",
    "Written in the Sand Old Dominion",
    "The Long Way Brett Eldredge",
    "Meant to Be (feat. Florida Georgia Line) Bebe Rexha, Florida Georgia Line",
    "Getting Over You Jackie Lee",
    "Marry Me Thomas Rhett",
    "What Ifs Kane Brown, Lauren Alaina",
    "Do I Make You Wanna Billy Currington",
    "Legends Kelsea Ballerini",
    "When It Rains It Pours Luke Combs",
    "Sunday Morning Parmalee",
    "Happens Like That Granger Smith",
  ],
};

const FRESH_ELECTRONIC = {
  name: 'Fresh Electronic',
  trackQueries: [
    "Kyoto Steve Brian",
    "Have a Fight Ed is Dead, Laia Vehí",
    "Runnin' EDX",
    "Cruel World Seeb, Skip Marley",
    "gold EDEN",
    "Dumbo Drop A-Trak, Baauer",
    "Way To Go Empire of the Sun",
    "No Captain - Edit Lane 8, POLIÇA",
    "The Unknown - Flite Remix Danny Chen, Ryan Ellingson, Flite",
    "Northern Soul Above & Beyond, Richard Bedford",
    "You and Me Shallou",
    "All I Want - Sons Of Maria Remix Alok, Liu, Stonefox, Sons Of Maria",
    "Falls (feat. Sasha Sloan) ODESZA, Sasha Sloan",
    "Murder Fangs",
    "Taj BLR, Rave & Crave",
    "Saint Bass City Rockers The Bloody Beetroots",
    "Piano Frank Walker, Emily Warren",
    "Astronaut - Something About Your Love Mansionair",
    "Touch the Ground (feat. Natalola) Cory Enemy, SYRE, Natalola",
    "Time for the Techno Carnage, VINAI",
    "Saying Nic Fanciulli, Damon Albarn",
    "Rise - Radio Edit Laidback Luke, Mark Villa",
    "Saints & Sinners - Habstrakt Remix Zomboy, Habstrakt",
    "All I Got Said the Sky, Kwesi",
    "Shine Good (feat. Julimar Santos) Garmiani, Julimar Santos",
    "No Coming Down NGHTMRE, Alex Wiley, Sky Montique",
    "Campfire 2017 - Sons of Maria Retouch Dinka, Sons Of Maria",
    "Waiting For Winter Gabriel & Dresden, Jan Burton",
    "Step Up Mike Williams, Tom & Jame",
    "Ghost Voices Virtual Self",
    "Tumbler Thomas Gold",
    "Say Hi Codeko, Austin Mahone",
    "Rather Do Tom Reason",
    "Other Worlds Bassnectar, Dorfex Bos",
    "Raw Madison Mars",
    "Happy Place Alison Wonderland",
    "Say A Little Prayer Moguai, Polina",
    "Problems Petit Biscuit, Lido",
    "Cold Hearted Seven Lions, Kill The Noise",
    "The Ghost Late Night Alumni",
    "Bonkers twoloud, Bounce Inc., Daav One",
    "Positive (feat. WRENN) Prince Fox, WRENN",
    "Walk Away Sick Individuals, Greyson Chance",
    "Somebody - Radio Edit SOVI",
    "Ha Leh Lou Ya Robin Schulz, Christy McDonald",
    "BTB Capa (Official)",
    "Four BT",
    "LOCO NERVO, Danny Avila, Reverie",
    "City Lights Palastic, Nevve",
    "Erase It MNYS",
  ],
};

module.exports = [
  ARE_AND_BE,
  ROCK_CLASSICS,
  CHRISTMAS_CLASSICS,
  GOLD_SCHOOL,
  ULTIMATE_INDIE,
  TOTALLY_ALTERNATIVE,
  HOT_COUNTRY,
  FRESH_ELECTRONIC,
];
